# Generated by Django 4.2.4 on 2023-11-05 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_contact_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentation',
            name='description',
        ),
    ]
